
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main


# env:
#   PROJECT_ID:
#   GKE_CLUSTER: cluster-1    # Add your cluster name here.
#   GKE_ZONE: us-central1-c   # Add your cluster zone here.
#   DEPLOYMENT_NAME: gke-test # Add your deployment name here.



jobs:

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Google auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.workload_identity_provider }}
          #'principalSet://iam.googleapis.com/projects/657990065782/locations/global/workloadIdentityPools/acount-test/*'
          #
        service_account: ${{ secrets.service_account }}
          #'github-account2@yefsah-hayet.iam.gserviceaccount.com'
          #{{ secrets.service_account }}

        # # Configure Docker to use the gcloud command-line tool as a credential
    # # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    #     gcloud --quiet auth configure-docker europe-west1-docker.pkg.dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.main
        push: true
        tags: europe-west1-docker.pkg.dev/yefsah-hayet/repo/flux:latest

  # # Get the GKE credentials so we can deploy to the cluster
  #   - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
  #     with:
  #       cluster_name: app-cluster
  #       location: europe-west1
  #       # credentials: {{ secrets.GKE_SA_KEY }}

    # # Setup gcloud CLI
    # - uses: google-github-actions/setup-gcloud@v0
    #   with:
    #     service_account_key: {{ secrets.GKE_SA_KEY }}
    #     project_id: {{ secrets.GKE_PROJECT }}

    # - name: push to gcr
    #   uses: RafikFarhad/push-to-gcr-github-action@v5-beta
    #   with:
    #     gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
    #     registry: eu.gcr.io
    #     project_id: yefsah-hayet
    #     image_name: repo/app_flask
    #     image_tag: ${{github.sha}}
    #     dockerfile: ./Dockerfile.main
    #     context: .


    # # Configure Docker to use the gcloud command-line tool as a credential
    # # helper for authentication


    # # Build the Docker image
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
    #   with:
    #     context: .
    #     file: ./ARCH-adservice/Dockerfile
    #     push: true
    #     tags: "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
    #  labels: {{ steps.meta.outputs.labels }}

    # - name: Build
    #   run: |-
    #     docker build  \
    #       --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
    #       --build-arg GITHUB_SHA="$GITHUB_SHA" \
    #       --build-arg GITHUB_REF="$GITHUB_REF" \
    #       .

    # Push the Docker image to Google Container Registry
    # - name: Publish
    #   run: |-
    #     docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"Â²

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build ./ARCH-adservice/manifest | kubectl apply -f -


    # kubectl rollout status deployment/$DEPLOYMENT_NAME
    # kubectl get services -o wide
